### ISSUE TITLE
Getting Error Put Copper in Smelter

### ISSUE THREAD

**Issue by lightsourced** [blaxxun-boop/ConversionSizeAndSpeed#4] opened 2022-04-19 09:22 UTC
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ConversionSizeSpeed.ConversionSizeSpeed+FillAllOres.Prefix (Smelter __instance, ItemDrop+ItemData item, System.Collections.Generic.KeyValuePair`2[ItemDrop+ItemData,System.Int32]& __state) (at <7bf17d7149184dd7b42f0174e18bcd5e>:0)
(wrapper dynamic-method) Smelter.DMD<Smelter::OnAddOre>(Smelter,Switch,Humanoid,ItemDrop/ItemData)
Switch.Interact (Humanoid character, System.Boolean hold, System.Boolean alt) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

Keep getting this error when attempting to put copper ore into the furnace. Both one at a time and also with Shift+E

We are using this mod: https://valheim.thunderstore.io/package/LukaWolf/CraftingWithContainersTempFix/
I have tried with it configured to not pull for furnace&kiln and when I have it set up that way I cannot put ores into the furnace or wood into the kiln at all, despite having the items in my inventory. When I set those options to true, I can single put items into the kiln/furnace but the Shift+E functionality no longer works.

**Comment by lightsourced** [comment] 2022-04-25 17:45
Really hoping you might be able to solve the mystery on this one and come up with a fix for this. I had to remove it from my modlist for the time being because we continue to not be able to add any resources to the kiln/furnace and really missing it! If you need me to try any additional testing to help, let me know!

**Comment by blaxxun-boop** [comment] 2022-05-12 21:31
Sorry for taking so long, I was unable to reproduce this issue. Should be fixed in v1.0.3 now, hopefully.

**Closed as completed by blaxxun-boop** 2022-05-12 21:31 UTC
